name: CI
on:
  push:
    branches: [main]  
  pull_request:

permissions:
  contents: read


jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Trivy (config & fs)
        uses: aquasecurity/trivy-action@0.26.0
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'